apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-env

resources:
  - ./namespaces.yaml
  - ../../base

# Staging environment specific configuration
images:
  - name: mongo
    newTag: "5.0"

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
    target:
      kind: Deployment
      name: webapp