apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-env

resources:
  - ./namespaces.yaml
  - ../../base

# Staging environment specific configuration

# Set the mongo image to be v5.0
images:
  - name: mongo
    newTag: "5.0"

# Increase the memory on the webapp
patchesStrategicMerge:
  - ./patch-webapp.yaml

# Label all pods as staging
patches:
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels/environment
        value: "staging"
      - op: add
        path: /metadata/labels/environment
        value: "staging"        
    target:
      kind: Deployment
